name: 💡 Enhancement
description: Propose an enhancement
title: 'Enhancement: '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |

        💡 Thanks for taking the time to suggest an improvement!

        This extension is built for clear bug reporting
        and intentionally stays focused and minimal.

        Please note that requests which significantly increase complexity
        or shift the tool toward general image editing may not be a good fit
        and are likely to be closed.

  - type: textarea
    id: problem
    attributes:
      label: What problem did you encounter?
      placeholder: |
        Example: Screenshots include sensitive data that should not be shared.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: |
        Example: Add a blur tool to hide sensitive data.
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope check
      options:
        - label: This request improves bug reporting, not general image editing
          required: true
