name: 💡 Feature request
description: Suggest a focused improvement or enhancement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ℹ️ Before you continue

        **Houston, we have a bug** is designed for *quick bug reporting*:
        capturing screenshots, adding simple annotations, and sharing context.

        It is **not** intended to be a full-featured drawing or design tool.
        Requests for complex illustration workflows, advanced editing,
        or design-software-level features are out of scope.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the limitation you are facing while reporting a bug.
      placeholder: |
        Good example:
        When annotating screenshots, it's hard to keep arrows aligned
        when pointing to UI elements.

        ❌ Not ideal:
        I want to freely draw complex shapes like in Figma or Photoshop.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Suggest a simple, focused improvement.
      placeholder: |
        Good example:
        Add snap-to-horizontal / snap-to-vertical behavior for arrows
        when holding a modifier key.

        ❌ Not ideal:
        Add layers, blending modes, and advanced vector editing.
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Why is this useful for bug reporting?
      description: Explain how this improves clarity or speed when reporting bugs.
      placeholder: |
        Example:
        This would make it faster to clearly point to misaligned UI elements
        without spending time adjusting arrows manually.
    validations:
      required: true

  - type: checkboxes
    id: scope_check
    attributes:
      label: Scope check
      options:
        - label: This request focuses on bug reporting, not general drawing or design
          required: true
