name: 💡 Improvement
description: Propose an improvement
title: "Improvement: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |

        ⚠️ Read before submitting

        This extension is built for **clear and fast bug reporting**.
        It intentionally stays minimal.

        Requests that significantly increase complexity or turn this into
        a general drawing or design tool are likely to be closed.

  - type: textarea
    id: problem
    attributes:
      label: What problem did you encounter?
      placeholder: |
        Example: Screenshots include sensitive data that should not be shared.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: |
        Example: Add a blur tool to hide sensitive data.
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope check
      options:
        - label: This request improves bug reporting, not general image editing
          required: true
